### PR TITLE
Migration to swift 3.0

### PR DESCRIPTION
**Pull request by vinzen**
Migration to swift 3.0

### CODE REVIEW

**Comment by bre7** [comment]
Hi, new with Toucan here but shouldn't the Toucan class be just public ? There's no reason to subclass is there ?

**Comment by vinzen** [comment]
The Toucan class is public

**Comment by bre7** [comment]
> -public class Toucan : NSObject {
+open class Toucan : NSObject {

**Comment by gavinbunney** [comment]
Thanks @vinzen ! I'll merge your bits with the other Swift3 branches

**Pull request closed without merging**
